namespace System.Data.Design
{
    using System;
    using System.ComponentModel;
    using System.Data;
    using System.Runtime;

    [DataSourceXmlClass("Parameter")]
    internal class DesignParameter : DataSourceComponent, IDbDataParameter, IDataParameter, IDataSourceNamedObject, INamedObject, ICloneable
    {
        private static int[] adoDataType2DbType = new int[] { 
            8, 0, 20, 12, 0x80, 1, 11, 3, 0x81, 0, 6, 4, 7, 5, 0x85, 5, 
            0x86, 6, 0x87, 6, 14, 7, 5, 8, 0, 13, 10, 13, 0x40, 6, 0x48, 9, 
            9, 13, 13, 13, 3, 11, 0xcd, 1, 0xc9, 0, 0xcb, 0x10, 0x83, 7, 0x8a, 13, 
            4, 15, 2, 10, 0x10, 14, 0x15, 20, 0x13, 0x13, 0x12, 0x12, 0x11, 2, 0xcc, 1, 
            200, 0, 0x8b, 0x15, 0xca, 0x10, 12, 13, 130, 0x10
         };
        private bool allowDbNull;
        private string autogeneratedName;
        private string columnName;
        private string dataSourceName;
        private string dataTypeServer;
        private System.Data.DbType dbType;
        public const string DEFAULT_RETVAL_NAME = "RETURN_VALUE";
        private ParameterDirection direction;
        private string parameterName;
        private byte precision;
        private string providerType;
        private byte scale;
        private int size;
        private string sourceColumn;
        private bool sourceColumnNullMapping;
        private DataRowVersion sourceVersion;

        public DesignParameter() : this(string.Empty)
        {
        }

        public DesignParameter(string name)
        {
            this.parameterName = name;
            this.autogeneratedName = string.Empty;
            this.direction = ParameterDirection.Input;
            this.sourceVersion = DataRowVersion.Current;
            this.dataSourceName = string.Empty;
        }

        public object Clone()
        {
            return new DesignParameter(this.ParameterName) { ColumnName = this.ColumnName, AutogeneratedName = this.AutogeneratedName, DbType = this.DbType, Precision = this.Precision, Scale = this.Scale, Size = this.Size, DataTypeServer = this.DataTypeServer, Direction = this.Direction, SourceColumn = this.SourceColumn, SourceVersion = this.SourceVersion, SourceColumnNullMapping = this.SourceColumnNullMapping };
        }

        public override bool Equals(object o)
        {
            DesignParameter parameter = o as DesignParameter;
            if (parameter == null)
            {
                return false;
            }
            return parameter.ParameterName.Equals(this.ParameterName);
        }

        public static DesignParameter GetDefaultRetvalParam()
        {
            DesignParameter parameter=null;
            return new DesignParameter("RETURN_VALUE") { DbType = System.Data.DbType.Int32, Precision = (byte) (parameter.Scale = 0), Size = 4, Direction = ParameterDirection.ReturnValue };
        }

        public override int GetHashCode()
        {
            return this.ParameterName.GetHashCode();
        }

        [TargetedPatchingOptOut("Performance critical to inline this type of method across NGen image boundaries")]
        public override string ToString()
        {
            return this.ParameterName;
        }

        [DataSourceXmlAttribute, DefaultValue(false)]
        public bool AllowDbNull
        {
            [TargetedPatchingOptOut("Performance critical to inline this type of method across NGen image boundaries")]
            get
            {
                return this.allowDbNull;
            }
            [TargetedPatchingOptOut("Performance critical to inline this type of method across NGen image boundaries")]
            set
            {
                this.allowDbNull = value;
            }
        }

        [DataSourceXmlAttribute, Browsable(false)]
        public string AutogeneratedName
        {
            [TargetedPatchingOptOut("Performance critical to inline this type of method across NGen image boundaries")]
            get
            {
                return this.autogeneratedName;
            }
            [TargetedPatchingOptOut("Performance critical to inline this type of method across NGen image boundaries")]
            set
            {
                this.autogeneratedName = value;
            }
        }

        [DataSourceXmlAttribute]
        public string ColumnName
        {
            [TargetedPatchingOptOut("Performance critical to inline this type of method across NGen image boundaries")]
            get
            {
                return this.columnName;
            }
            [TargetedPatchingOptOut("Performance critical to inline this type of method across NGen image boundaries")]
            set
            {
                this.columnName = value;
            }
        }

        [DataSourceXmlAttribute, Browsable(false)]
        public string DataSourceName
        {
            [TargetedPatchingOptOut("Performance critical to inline this type of method across NGen image boundaries")]
            get
            {
                return this.dataSourceName;
            }
            [TargetedPatchingOptOut("Performance critical to inline this type of method across NGen image boundaries")]
            set
            {
                this.dataSourceName = value;
            }
        }

        [Browsable(false), DataSourceXmlAttribute]
        public string DataTypeServer
        {
            [TargetedPatchingOptOut("Performance critical to inline this type of method across NGen image boundaries")]
            get
            {
                return this.dataTypeServer;
            }
            [TargetedPatchingOptOut("Performance critical to inline this type of method across NGen image boundaries")]
            set
            {
                this.dataTypeServer = value;
            }
        }

        [DataSourceXmlAttribute]
        public System.Data.DbType DbType
        {
            [TargetedPatchingOptOut("Performance critical to inline this type of method across NGen image boundaries")]
            get
            {
                return this.dbType;
            }
            [TargetedPatchingOptOut("Performance critical to inline this type of method across NGen image boundaries")]
            set
            {
                this.dbType = value;
            }
        }

        [DataSourceXmlAttribute, DefaultValue(1)]
        public ParameterDirection Direction
        {
            [TargetedPatchingOptOut("Performance critical to inline this type of method across NGen image boundaries")]
            get
            {
                return this.direction;
            }
            [TargetedPatchingOptOut("Performance critical to inline this type of method across NGen image boundaries")]
            set
            {
                this.direction = value;
            }
        }

        [DefaultValue(false), DesignOnly(true), EditorBrowsable(EditorBrowsableState.Never), Browsable(false)]
        public bool IsNullable
        {
            get
            {
                return true;
            }
        }

        [Browsable(false)]
        public string Name
        {
            [TargetedPatchingOptOut("Performance critical to inline this type of method across NGen image boundaries")]
            get
            {
                return this.ParameterName;
            }
        }

        [DefaultValue(""), DataSourceXmlAttribute, MergableProperty(false)]
        public string ParameterName
        {
            [TargetedPatchingOptOut("Performance critical to inline this type of method across NGen image boundaries")]
            get
            {
                return this.parameterName;
            }
            set
            {
                if (!StringUtil.EqualValue(this.ParameterName, value))
                {
                    if (this.CollectionParent != null)
                    {
                        this.CollectionParent.ValidateUniqueName(this, value);
                    }
                    this.parameterName = value;
                }
            }
        }

        [DefaultValue((byte) 0), DataSourceXmlAttribute]
        public byte Precision
        {
            [TargetedPatchingOptOut("Performance critical to inline this type of method across NGen image boundaries")]
            get
            {
                return this.precision;
            }
            [TargetedPatchingOptOut("Performance critical to inline this type of method across NGen image boundaries")]
            set
            {
                this.precision = value;
            }
        }

        [DataSourceXmlAttribute]
        public string ProviderType
        {
            [TargetedPatchingOptOut("Performance critical to inline this type of method across NGen image boundaries")]
            get
            {
                return this.providerType;
            }
            [TargetedPatchingOptOut("Performance critical to inline this type of method across NGen image boundaries")]
            set
            {
                this.providerType = value;
            }
        }

        [DefaultValue((byte) 0), DataSourceXmlAttribute]
        public byte Scale
        {
            [TargetedPatchingOptOut("Performance critical to inline this type of method across NGen image boundaries")]
            get
            {
                return this.scale;
            }
            [TargetedPatchingOptOut("Performance critical to inline this type of method across NGen image boundaries")]
            set
            {
                this.scale = value;
            }
        }

        [DataSourceXmlAttribute, DefaultValue(0)]
        public int Size
        {
            [TargetedPatchingOptOut("Performance critical to inline this type of method across NGen image boundaries")]
            get
            {
                return this.size;
            }
            set
            {
                this.size = value;
                if (this.size < 0)
                {
                    this.size = 0x7fffffff;
                }
            }
        }

        [DefaultValue(""), DataSourceXmlAttribute]
        public string SourceColumn
        {
            [TargetedPatchingOptOut("Performance critical to inline this type of method across NGen image boundaries")]
            get
            {
                return this.sourceColumn;
            }
            [TargetedPatchingOptOut("Performance critical to inline this type of method across NGen image boundaries")]
            set
            {
                this.sourceColumn = value;
            }
        }

        [DefaultValue(false), DataSourceXmlAttribute]
        public bool SourceColumnNullMapping
        {
            [TargetedPatchingOptOut("Performance critical to inline this type of method across NGen image boundaries")]
            get
            {
                return this.sourceColumnNullMapping;
            }
            [TargetedPatchingOptOut("Performance critical to inline this type of method across NGen image boundaries")]
            set
            {
                this.sourceColumnNullMapping = value;
            }
        }

        [DataSourceXmlAttribute, DefaultValue(0x200)]
        public DataRowVersion SourceVersion
        {
            [TargetedPatchingOptOut("Performance critical to inline this type of method across NGen image boundaries")]
            get
            {
                return this.sourceVersion;
            }
            [TargetedPatchingOptOut("Performance critical to inline this type of method across NGen image boundaries")]
            set
            {
                this.sourceVersion = value;
            }
        }

        string IDataSourceNamedObject.PublicTypeName
        {
            get
            {
                return "Parameter";
            }
        }

        string INamedObject.Name
        {
            [TargetedPatchingOptOut("Performance critical to inline this type of method across NGen image boundaries")]
            get
            {
                return this.ParameterName;
            }
            [TargetedPatchingOptOut("Performance critical to inline this type of method across NGen image boundaries")]
            set
            {
                this.ParameterName = value;
            }
        }

        [Browsable(false), DefaultValue((string) null)]
        public object Value
        {
            get
            {
                return null;
            }
            set
            {
            }
        }
    }
}

